### ISSUE TITLE
Failing on container creation for registry

### ISSUE THREAD

**Issue by larsxsamuelsson** [Kubeinit/kubeinit#113]
Setting up a completely new and vanilla setup with this. I end up with this error on CentOS 8, whether I run it directly or from podman, this same error appears. Wondering what I'm doing wrong, but thought a github issue might point me in the right direction :-) 

TASK [../../roles/kubeinit_registry : Create container to serve the registry] *********************************************************
fatal: [hypervisor-01 -> 10.0.0.100]: FAILED! => {"changed": false, "msg": "Can't create container kubeinit-registry", "stderr": "Error: unknown flag: --detach\n", "stderr_lines": ["Error: unknown flag: --detach"], "stdout": "", "stdout_lines": []}

**Comment by ccamacho** [comment]
Hi @larsxsamuelsson, first thanks for raising this issue.

Hi, yeah I'm hitting the exact same issue, so you should be doing things fine 👍 
That particular issue I believe is the podman ansible module failing but I'm not sure yet why it fails.

I'll use this for tracking this issue, it affects master and any release and ping you when it's working again.

Please feel free to ask any questions you have, and if you find any issue also feel free to raise issues in the project's repo (https://www.github.com/kubeinit/kubeinit). Also, it would be awesome if you can star the project to catch up with updates and new features.

**Comment by larsxsamuelsson** [comment]
@ccamacho awesome! Thanks for the almost insanely quick reply :-D

**Comment by ccamacho** [comment]
Also skopeo was recently updated.. and broken :/ https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/x86_64/

**Comment by ccamacho** [comment]
```
[MIRROR] skopeo-1.2.0-9.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 12764528 but expected size is: 12764544                                             

[MIRROR] containers-common-1.2.0-9.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 91656 but expected size is: 91664                                        

[MIRROR] skopeo-1.2.0-9.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 12764528 but expected size is: 12764544                                             

[MIRROR] containers-common-1.2.0-9.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 91656 but expected size is: 91664                                        

[FAILED] containers-common-1.2.0-9.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
```

**Comment by ccamacho** [comment]
Tracked here: https://bugzilla.opensuse.org/show_bug.cgi?id=1179487

**Comment by ccamacho** [comment]
The podman package was updated in the kubic project, thus the flag is broken:

```
[root@okd-service-01 ~]# yum --showduplicates list podman
Last metadata expiration check: 0:07:30 ago on Wed 02 Dec 2020 07:27:24 AM UTC.
Installed Packages
podman.x86_64                        2.2.0-1.el8                       @devel_kubic_libcontainers_stable
```

**Comment by ccamacho** [comment]
@larsxsamuelsson yeah, lot's of things broke after the latest packages update, I only have one distro left to fix
https://github.com/Kubeinit/kubeinit/pull/111

**Comment by ccamacho** [comment]
@larsxsamuelsson it should work now using master, Ill create another release soon

**Comment by larsxsamuelsson** [comment]
@ccamacho I ended up with this:
TASK [Configure the cluster service node] *********************************************************************************************
ERROR! couldn't resolve module/action 'community.general.docker_login'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/kubeinit/kubeinit/roles/kubeinit_registry/tasks/00_install.yml': line 59, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Log into DockerHub
  ^ here

Running from master now.

**Comment by ccamacho** [comment]
@larsxsamuelsson can you upgrade to the latest ansible version?

**Comment by ccamacho** [comment]
darn the CI is filling those variables, Im validating it now.. sorry **almost fixed.

**Comment by larsxsamuelsson** [comment]
@ccamacho i did update to 2.10.4 (in the meantime) but then i end up with getting stuck here:
TASK [../../roles/kubeinit_registry : Podman login to docker.io] *****************************************************************************************************************************************************************************

:-) it just halts there, does not die.. it is just stuck without doing anything it seems.

**Comment by ccamacho** [comment]
@larsxsamuelsson :P now it should work, I just tested it and it seems to deploy correctly fixed the login issues here in https://github.com/Kubeinit/kubeinit/pull/114 .. all this mess thanks to the new packages released in the kubic repos...

**Comment by larsxsamuelsson** [comment]
@ccamacho It very much does! :-D Verified this morning and everything works out fine. Now I will go on to see what I have screwed up when it comes to external access. But that problem I had before as well.

closing this one.
