### ISSUE TITLE
Install failing after centos 8 current updates

### ISSUE THREAD

**Issue by tlhconsulting** [Kubeinit/kubeinit#134]
Failing to Install

Seems the install file is missing

internal error: child reported (status=125): unable to stat: /var/lib/libvirt/boot/virtinst-sueu1m4i-fedora-coreos-32.20200715.3.0-live-kernel-x86_64: No such file or directory

I traced it to this

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-Troubleshooting-Common_libvirt_errors_and_troubleshooting#sect-Migration_fails_with_Unable_to_allow_access_for_disk_path_No_such_file_or_directory

**Comment by ccamacho** [comment]
Hi @tlhconsulting thanks for reporting this, I didn't see this issue after the packages update in CentOS, I know multiple things broke and fixed now.

- Can you put the output of the Ansible task that failed?
- Are you using latest master?

I know this https://github.com/Kubeinit/kubeinit/issues/135 is the only thing still failing randomly that I can spot.

**Comment by tlhconsulting** [comment]
I updated to 0.6.2 as you suggested and now getting a rate limit error for docker hub. can you tell me where in the code this is set. I have an updated plan that should allow me access.

TASK [../../roles/kubeinit_registry : Create a docker container to serve the registry] **************************************************************************************************************
[DEPRECATION WARNING]: The container_default_behavior option will change its default value from "compatibility" to "no_defaults" in community.general 3.0.0. To remove this warning, please specify 
an explicit value for it now. This feature will be removed in version 3.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [hypervisor-01 -> 192.168.5.100]: FAILED! => {"changed": false, "msg": "Error pulling image docker.io/library/registry:2 - 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2&fromImage=docker.io%2Flibrary%2Fregistry: Internal Server Error (\"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit\")"}

**Comment by tlhconsulting** [comment]
Another install no errors this time, but also no console access. I did provide the username and password for my account as environment variables but no success in reaching the console.

**Comment by ccamacho** [comment]
@tlhconsulting yeah, the limit rate is PITA to be honest, when you run the ansible playbook you need to update these 2 variables:
https://github.com/Kubeinit/kubeinit/blob/master/kubeinit/hosts/common.yml#L3

Like:

```
ansible-playbook \
    --user root \
    -v -i ./hosts/okd/inventory \
    -e kubeinit_common_docker_username=user \
    -e kubeinit_common_docker_password=pass \
    --become \
    --become-user root \
    ./playbooks/okd.yml
```

What do you mean by console access? The user/pass fails?, you can not reach the IP where the console is deployed?, or you can not ssh to the nodes?

If the user/pass fails check here for the kubeadmin password:
```
cat ~install_dir/auth/kubeadmin-password
aaxkv-Z5sV3-9jeE2-nQ7Wh
```

The IP access is explained here:
https://www.anstack.com/blog/2020/08/25/KubeInit-External-access-for-OpenShift-OKD-deployments-with-Libvirt.html

To ssh into the nodes use
ssh root@10.0.0.100 -> service node
ssh core@10.0.0.[1-3|6-...] the master or worker nodes (running with FCOS)

**Comment by tlhconsulting** [comment]
TASK [../../roles/kubeinit_registry : Create a docker container to serve the registry] ******************************************************************************************************
[DEPRECATION WARNING]: The container_default_behavior option will change its default value from "compatibility" to "no_defaults" in community.general 3.0.0. To remove this warning, please 
specify an explicit value for it now. This feature will be removed in version 3.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [hypervisor-01 -> 192.168.5.100]: FAILED! => {"changed": false, "msg": "Error pulling image docker.io/library/registry:2 - 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2&fromImage=docker.io%2Flibrary%2Fregistry: Internal Server Error (\"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\")"}

Most Recent Error:

By console access I mean I cannot reach the console-openshift-console.apps.clustername0.kubeinit.local I can reach the individual nodes.

**Comment by tlhconsulting** [comment]
I am a bit confused around some discussion graphics use enp0 enp1 and configuration files use eth0, eth1, eth2. Can you explain these differences, I am trying to get a sense of the structure and use of these ?
In the inventory file you have okd_service_nodes with devicename of eth0, and kubeinit_inventory_network_bridge_external_dev=eth1

**Comment by tlhconsulting** [comment]
OK found my issues they were all with the configuration, changing the base inventory file to add in the options for setting some options in the inventory_network_bridge_external through me completely off track. I got all the right configuration in place and it works again. Sorry for any inconvenience but your help is greatly appreciated.
