### ISSUE TITLE
[10_configure.yml] - 'dict object' has no attribute 'ansible_facts'

### ISSUE THREAD

**Issue by danielyeap** [Kubeinit/kubeinit#169]
TASK [../../roles/kubeinit_registry : Setting Docker facts about the container that will run the registry] ********************************************************************************************************
task path: /home/danielyeap/ansible/kubeinit/kubeinit/roles/kubeinit_registry/tasks/10_configure.yml:244
fatal: [hypervisor-01]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ansible_facts'\n\nThe error appears to be in '/home/danielyeap/ansible/kubeinit/kubeinit/roles/kubeinit_registry/tasks/10_configure.yml': line 244, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Setting Docker facts about the container that will run the registry\n  ^ here\n"
}

===============

TASK [../../roles/kubeinit_registry : debug] **********************************************************************************************************************************************************************
task path: /home/danielyeap/ansible/kubeinit/kubeinit/roles/kubeinit_registry/tasks/10_configure.yml:240
ok: [hypervisor-01 -> 10.0.0.100] => {
    "registry_docker_container_info": {
        "changed": true,
        "container": {
            "AppArmorProfile": "",
            "Args": [
                "/etc/docker/registry/config.yml"
            ],
            "Config": {
                "AttachStderr": false,
                "AttachStdin": false,
                "AttachStdout": false,
                "Cmd": [
                    "/etc/docker/registry/config.yml"
                ],
                "Domainname": "",
                "Entrypoint": [
                    "/entrypoint.sh"
                ],
                "Env": [
                    "REGISTRY_AUTH=htpasswd",
                    "REGISTRY_AUTH_HTPASSWD_REALM=Registry",
                    "REGISTRY_HTTP_SECRET=ALongRandomSecretForRegistry",
                    "REGISTRY_AUTH_HTPASSWD_PATH=auth/htpasswd",
                    "REGISTRY_HTTP_TLS_CERTIFICATE=certs/domain.crt",
                    "REGISTRY_HTTP_TLS_KEY=certs/domain.key",
                    "REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED=true",
                    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
                ],
                "ExposedPorts": {
                    "5000/tcp": {}
                },
                "Hostname": "6f2a5b61a503",
                "Image": "docker.io/library/registry:2",
                "Labels": {},
                "OnBuild": null,
                "OpenStdin": false,
                "StdinOnce": false,
                "Tty": false,
                "User": "",
                "Volumes": {
                    "/var/lib/registry": {}
                },
                "WorkingDir": ""
            },
            "Created": "2021-02-05T09:04:12.281946781Z",
            "Driver": "overlay2",
            "ExecIDs": null,
            "GraphDriver": {
                "Data": {
                    "LowerDir": "/var/lib/docker/overlay2/ced18f790db72ba967cec3696c405376a9e40bd02e7258a0f6b7ddb04363f772-init/diff:/var/lib/docker/overlay2/c2f7e0160242e599b0a5d6914f346fef28e4e530727ab0f7a8cf60335731cb8d/diff:/var/lib/docker/overlay2/d2612f20e5d9c7cc524c59ef83a21710bbf7f7debefb410294228d731e693ca7/diff:/var/lib/docker/overlay2/d3bf4b65f7cea7cffafeb645a291cb7b563d5fdb2a82612ae9645c35a592623f/diff:/var/lib/docker/overlay2/ebd652c8211b52ec3591fc2e95b10506f9109bbef8816a1adb1bcab9ea036ceb/diff:/var/lib/docker/overlay2/503e8675b9491750dedfaab5292962bb6b63bccf4a5827063ce317a3c09d1b3c/diff",
                    "MergedDir": "/var/lib/docker/overlay2/ced18f790db72ba967cec3696c405376a9e40bd02e7258a0f6b7ddb04363f772/merged",
                    "UpperDir": "/var/lib/docker/overlay2/ced18f790db72ba967cec3696c405376a9e40bd02e7258a0f6b7ddb04363f772/diff",
                    "WorkDir": "/var/lib/docker/overlay2/ced18f790db72ba967cec3696c405376a9e40bd02e7258a0f6b7ddb04363f772/work"
                },
                "Name": "overlay2"
            },
            "HostConfig": {
                "AutoRemove": false,
                "Binds": [
                    "/var/kubeinit/local_registry/data:/var/lib/registry:z",
                    "/var/kubeinit/local_registry/auth:/auth:z",
                    "/var/kubeinit/local_registry/certs:/certs:z"
                ],
                "BlkioDeviceReadBps": null,
                "BlkioDeviceReadIOps": null,
                "BlkioDeviceWriteBps": null,
                "BlkioDeviceWriteIOps": null,
                "BlkioWeight": 0,
                "BlkioWeightDevice": null,
                "CapAdd": null,
                "CapDrop": null,
                "Cgroup": "",
                "CgroupParent": "",
                "CgroupnsMode": "host",
                "ConsoleSize": [
                    0,
                    0
                ],
                "ContainerIDFile": "",
                "CpuCount": 0,
                "CpuPercent": 0,
                "CpuPeriod": 0,
                "CpuQuota": 0,
                "CpuRealtimePeriod": 0,
                "CpuRealtimeRuntime": 0,
                "CpuShares": 0,
                "CpusetCpus": "",
                "CpusetMems": "",
                "DeviceCgroupRules": null,
                "DeviceRequests": null,
                "Devices": null,
                "Dns": null,
                "DnsOptions": null,
                "DnsSearch": null,
                "ExtraHosts": null,
                "GroupAdd": null,
                "IOMaximumBandwidth": 0,
                "IOMaximumIOps": 0,
                "Init": false,
                "IpcMode": "private",
                "Isolation": "",
                "KernelMemory": 0,
                "KernelMemoryTCP": 0,
                "Links": null,
                "LogConfig": {
                    "Config": {},
                    "Type": "json-file"
                },
                "MaskedPaths": [
                    "/proc/asound",
                    "/proc/acpi",
                    "/proc/kcore",
                    "/proc/keys",
                    "/proc/latency_stats",
                    "/proc/timer_list",
                    "/proc/timer_stats",
                    "/proc/sched_debug",
                    "/proc/scsi",
                    "/sys/firmware"
                ],
                "Memory": 0,
                "MemoryReservation": 0,
                "MemorySwap": 0,
                "MemorySwappiness": null,
                "NanoCpus": 0,
                "NetworkMode": "default",
                "OomKillDisable": false,
                "OomScoreAdj": 0,
                "PidMode": "host",
                "PidsLimit": null,
                "PortBindings": {
                    "5000/tcp": [
                        {
                            "HostIp": "0.0.0.0",
                            "HostPort": "5000"
                        }
                    ]
                },
                "Privileged": false,
                "PublishAllPorts": false,
                "ReadonlyPaths": [
                    "/proc/bus",
                    "/proc/fs",
                    "/proc/irq",
                    "/proc/sys",
                    "/proc/sysrq-trigger"
                ],
                "ReadonlyRootfs": false,
                "RestartPolicy": {
                    "MaximumRetryCount": 0,
                    "Name": ""
                },
                "Runtime": "runc",
                "SecurityOpt": [
                    "label=disable"
                ],
                "ShmSize": 67108864,
                "UTSMode": "",
                "Ulimits": null,
                "UsernsMode": "",
                "VolumeDriver": "",
                "VolumesFrom": null
            },
            "HostnamePath": "/var/lib/docker/containers/6f2a5b61a503b63b3442b7c72bb485dce2dc65b169810a46b0b6cc12b44c3159/hostname",
            "HostsPath": "/var/lib/docker/containers/6f2a5b61a503b63b3442b7c72bb485dce2dc65b169810a46b0b6cc12b44c3159/hosts",
            "Id": "6f2a5b61a503b63b3442b7c72bb485dce2dc65b169810a46b0b6cc12b44c3159",
            "Image": "sha256:678dfa38fcfa349ccbdb1b6d52ac113ace67d5746794b36dfbad9dd96a9d1c43",
            "LogPath": "/var/lib/docker/containers/6f2a5b61a503b63b3442b7c72bb485dce2dc65b169810a46b0b6cc12b44c3159/6f2a5b61a503b63b3442b7c72bb485dce2dc65b169810a46b0b6cc12b44c3159-json.log",
            "MountLabel": "",
            "Mounts": [
                {
                    "Destination": "/var/lib/registry",
                    "Mode": "z",
                    "Propagation": "rprivate",
                    "RW": true,
                    "Source": "/var/kubeinit/local_registry/data",
                    "Type": "bind"
                },
                {
                    "Destination": "/auth",
                    "Mode": "z",
                    "Propagation": "rprivate",
                    "RW": true,
                    "Source": "/var/kubeinit/local_registry/auth",
                    "Type": "bind"
                },
                {
                    "Destination": "/certs",
                    "Mode": "z",
                    "Propagation": "rprivate",
                    "RW": true,
                    "Source": "/var/kubeinit/local_registry/certs",
                    "Type": "bind"
                }
            ],
            "Name": "/kubeinit-registry",
            "NetworkSettings": {
                "Bridge": "",
                "EndpointID": "b1ae8d7016e444c0c2583d6bb66c99c122fc487facbd6cdf2b50428695ab5149",
                "Gateway": "172.17.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "HairpinMode": false,
                "IPAddress": "172.17.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "LinkLocalIPv6Address": "",
                "LinkLocalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:02",
                "Networks": {
                    "bridge": {
                        "Aliases": null,
                        "DriverOpts": null,
                        "EndpointID": "b1ae8d7016e444c0c2583d6bb66c99c122fc487facbd6cdf2b50428695ab5149",
                        "Gateway": "172.17.0.1",
                        "GlobalIPv6Address": "",
                        "GlobalIPv6PrefixLen": 0,
                        "IPAMConfig": null,
                        "IPAddress": "172.17.0.2",
                        "IPPrefixLen": 16,
                        "IPv6Gateway": "",
                        "Links": null,
                        "MacAddress": "02:42:ac:11:00:02",
                        "NetworkID": "16e3cafffe012c6f4324771570c8d6a247fd118f7579e50ec338da9ec9b9cbb2"
                    }
                },
                "Ports": {
                    "5000/tcp": [
                        {
                            "HostIp": "0.0.0.0",
                            "HostPort": "5000"
                        }
                    ]
                },
                "SandboxID": "6b480a0c8ce1c8a81a422ff654582a183f339c542dff4ece2a2544cd03362c2f",
                "SandboxKey": "/var/run/docker/netns/6b480a0c8ce1",
                "SecondaryIPAddresses": null,
                "SecondaryIPv6Addresses": null
            },
            "Path": "/entrypoint.sh",
            "Platform": "linux",
            "ProcessLabel": "",
            "ResolvConfPath": "/var/lib/docker/containers/6f2a5b61a503b63b3442b7c72bb485dce2dc65b169810a46b0b6cc12b44c3159/resolv.conf",
            "RestartCount": 0,
            "State": {
                "Dead": false,
                "Error": "",
                "ExitCode": 0,
                "FinishedAt": "0001-01-01T00:00:00Z",
                "OOMKilled": false,
                "Paused": false,
                "Pid": 30997,
                "Restarting": false,
                "Running": true,
                "StartedAt": "2021-02-05T09:04:13.054022522Z",
                "Status": "running"
            }
        },
        "deprecations": [
            {
                "msg": "The container_default_behavior option will change its default value from \"compatibility\" to \"no_defaults\" in community.docker 2.0.0. To remove this warning, please specify an explicit value for it now",
                "version": "2.0.0"
            }
        ],
        "failed": false
    }
}

=============

What is wrong with the task? Can you please help as I am not that familiar with Ansible yet?

Thanks.

**Comment by ccamacho** [comment]
Hello @danielyeap, what version are you trying to deploy? Are you deploying from a container or from the git repo? That error came after moving to FQCN, so please try to use the latest code or from a released tag.

Please feel free to ask any questions you have, and if you find any issue also feel free to raise issues in the project's repo (https://www.github.com/kubeinit/kubeinit). You can jump in and ask in the slack channel https://kubernetes.slack.com/archives/C01FKK19T0B  Also, it would be awesome if you can star the project to catch up with updates and new features.
