### ISSUE TITLE
Task failed in role apply nfs security policy to nfs user

### ISSUE THREAD

**Issue by eurodrigolira** [Kubeinit/kubeinit#176]
I am getting the following error when deploying.

```
TASK [../../roles/kubeinit_nfs : add security context constraint for nfs provisioner] **************************************************************
fatal: [hypervisor-01 -> 10.0.0.100]: FAILED! => {"changed": false, "cmd": "cat << EOF > ~/nfs_scc.yaml\napiVersion: security.openshift.io/v1\nkind: SecurityContextConstraints\nmetadata:\n  name: nfs-provisioner\nallowHostDirVolumePlugin: true\nallowHostIPC: false\nallowHostNetwork: false\nallowHostPID: false\nallowHostPorts: false\nallowPrivilegedContainer: false\nallowedCapabilities:\n- DAC_READ_SEARCH\n- SYS_RESOURCE\ndefaultAddCapabilities: null\nfsGroup:\n  type: MustRunAs\npriority: null\nreadOnlyRootFilesystem: false\nrequiredDropCapabilities:\n- KILL\n- MKNOD\n- SYS_CHROOT\nrunAsUser:\n  type: RunAsAny\nseLinuxContext:\n  type: MustRunAs\nsupplementalGroups:\n  type: RunAsAny\nvolumes:\n- configMap\n- downwardAPI\n- emptyDir\n- hostPath\n- nfs\n- persistentVolumeClaim\n- secret\nEOF\nexport KUBECONFIG=~/.kube/config\nkubectl apply -f ~/nfs_scc.yaml\n", "delta": "0:00:04.823758", "end": "2021-02-07 06:43:29.773731", "msg": "non-zero return code", "rc": 1, "start": "2021-02-07 06:43:24.949973", "stderr": "error: unable to recognize \"/root/nfs_scc.yaml\": no matches for kind \"SecurityContextConstraints\" in version \"security.openshift.io/v1\"", "stderr_lines": ["error: unable to recognize \"/root/nfs_scc.yaml\": no matches for kind \"SecurityContextConstraints\" in version \"security.openshift.io/v1\""], "stdout": "", "stdout_lines": []}                                                                                                                 

PLAY RECAP *****************************************************************************************************************************************
hypervisor-01              : ok=222  changed=121  unreachable=0    failed=1    skipped=81   rescued=0    ignored=3   
```

Do you know why?

**Comment by ccamacho** [comment]
Hello can you give more infomation about how you are running the collection?

Can you try with latest master?

**Comment by eurodrigolira** [comment]
Hello,

The host is a virtual machine with CentOS 8.3.2011 running on ESXi 6.7 with nested mode enabled.

**Hardware Settings:**

128 GB RAM
700 GB M2 SSD Disk
4 vCPUs

I run the playbook straight from my desktop with Slackware Linux.

**Commands**

`git clone https://github.com/Kubeinit/kubeinit.git`

`cd kubeinit`

`ansible-galaxy collection install --force -r kubeinit/requirements.yml `

`ansible-playbook --user root -v -i ./hosts/okd/inventory --become --become-user root ./playbooks/okd.yml`

**Inventory**

**okd_master_nodes: (three master)**
ram=16777216
vcpus=4
maxvcpus=4

**okd_worker_nodes: (two worker)**
ram=16777216
vcpus=4
maxvcpus=4

**okd_service_nodes: (one node)**
ram=16777216
vcpus=4
maxvcpus=4

**okd_bootstrap_nodes: (one node)**
ram=16777216
vcpus=4
maxvcpus=4

Thanks for the reply.

**Comment by ccamacho** [comment]
I never tested it on a VM but it should work as long as nested virtualization is enabled. In the code you are running can you make sure that https://github.com/Kubeinit/kubeinit/blob/master/kubeinit/roles/kubeinit_okd/defaults/main.yml#L27 is like:

```
kubeinit_okd_wait_for_cluster_to_converge: True
```

That should make sure the deployment converges before trying to add those resources.

Also, I don't think 16GB will be enough for the master nodes maybe you are having some OOM issues there. Try with the default inventory and once you have it working customize it to your needs.

Please feel free to ask any questions you have, and if you find any issue also feel free to raise issues in the project's repo (https://www.github.com/kubeinit/kubeinit). You can jump in and ask in the slack channel https://kubernetes.slack.com/archives/C01FKK19T0B Also, it would be awesome if you can star the project to catch up with updates and new features.

**Comment by eurodrigolira** [comment]
I will test and post the result.

**Comment by ccamacho** [comment]
Feel free to reopen this if you find any issue
