### ISSUE TITLE
Issue on deploying okd-service-01 DNS-error?

### ISSUE THREAD

**Issue by mrrevillo0815** [Kubeinit/kubeinit#198]
Hello, thanks for this project and everyone working on it!

I have a problem when deploying (either via podman or directly with the ansible), i get this message:
```

TASK [Configure the cluster service node] **************************************

TASK [../../roles/kubeinit_okd : update packages] ******************************

fatal: [hypervisor-01 -> 10.0.0.100]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]", "rc": 1, "results": []}

PLAY RECAP *********************************************************************
hypervisor-01              : ok=86   changed=20   unreachable=0    failed=1    skipped=22   rescued=0    ignored=3  
```

When ssh-ing into the virutal machine (okd-service-01), i cannot do any yum installations and `curl google.com` fails as well with the same message.

I CAN `ping 8.8.8.8`, and the issue does not change when changing the `resolve.conf` file

Is it maybe a problem that i try to execute this deployment from the hypervisor-node itself?

I tried it with the release-branch as well as the current master branch, and my host is a centOS 8 machine

**Comment by ccamacho** [comment]
Hello!

Thanks for trying kubeinit.

It looks like you are not able to resolve using an external DNS, by default we use the value from kubeinit_common_dns_master defined in https://github.com/Kubeinit/kubeinit/blob/master/kubeinit/hosts/common.yml#L5

So, SSH into the service node (okd-service-01) and check the value of /etc/resolv.conf, you should have there 1.1.1.1

Change that value to whatever good DNS server works for you and try ping www.google.com

If it manages to resolve then just override that variable like:

ansible-playbook \
    -v \
    --user root \
    -i ./hosts/okd/inventory \
    --become \
    --become-user root \
    -e kubeinit_common_dns_master=8.8.8.8 \
    ./playbooks/okd.yml

Just let me know if that solves the problem for you!

**Comment by mrrevillo0815** [comment]
Thanks for the quick response!
That was it, thank you so much!

Strangely enough you were right, 1.1.1.1 was blocked; I just used the one that was described in my current `/etc/resolve.conf`, which was 8.8.8.8 as you suggested.

I am currently failing at this step now, but that is a different issue.
TASK [../../roles/kubeinit_okd : verify that all the csr are loaded and aproved for the deployed nodes] ***
