### ISSUE TITLE
Continue provisioning cluster after fixing bug

### ISSUE THREAD

**Issue by lapd-viosoft** [Kubeinit/kubeinit#20]
Hi @ccamacho 
Currently, if user has  any issues during the deployment, she/he need to fix something and retry again. Current behavior of kubeinit is destroying whole cluster and restart from scratch everything. It's great if kubeinit has an option to allow user to continue to provisioning cluster after fixing bugs.

**Comment by ccamacho** [comment]
@lapd-viosoft thanks a lot for the feedback, I moved all these issues as cards in a kanban project https://github.com/Kubeinit/kubeinit/projects/1 if you will like to contribute, please feel free to push any PR you will like to have included in the code. When I have some free time I'll try to implement some of them.
