### ISSUE TITLE
Add/remove worker nodes to/from deployed cluster

### ISSUE THREAD

**Issue by lapd-viosoft** [Kubeinit/kubeinit#21]
Hi @ccamacho,
Adding new worker nodes to deployed cluster is not easy now. It's actually deploy whole new cluster instead of adding new nodes.
It's better to support adding/removing worker nodes to/from deployed cluster.

**Comment by ccamacho** [comment]
@lapd-viosoft thanks a lot for the feedback, I moved all these issues as cards in a kanban project https://github.com/Kubeinit/kubeinit/projects/1 if you will like to contribute, please feel free to push any PR you will like to have included in the code. When I have some free time I'll try to implement some of them.
