### ISSUE TITLE
Autoscaling worker nodes

### ISSUE THREAD

**Issue by lapd-viosoft** [Kubeinit/kubeinit#22]
It's an advanced scenario where the worker nodes are auto spin up upon workload and current baremeal resources. It's just an idea. I'm not sure how we can support this scenario(may be it is needed an agent to monitor  cluster...and do adding/removing new nodes).

**Comment by ccamacho** [comment]
@lapd-viosoft thanks a lot for the feedback, I moved all these issues as cards in a kanban project https://github.com/Kubeinit/kubeinit/projects/1 if you will like to contribute, please feel free to push any PR you will like to have included in the code. When I have some free time I'll try to implement some of them.
