### ISSUE TITLE
Add more services to service node

### ISSUE THREAD

**Issue by lapd-viosoft** [Kubeinit/kubeinit#23]
This is an improvement where more E2E services are added such as:
- GitLab
- Artifactory
- Portainer
- Keycloak
- OpenLDAP
- Project Quay

**Comment by ccamacho** [comment]
@lapd-viosoft thanks a lot for the feedback, I moved all these issues as cards in a kanban project https://github.com/Kubeinit/kubeinit/projects/1 if you will like to contribute, please feel free to push any PR you will like to have included in the code. When I have some free time I'll try to implement some of them.
