### ISSUE TITLE
Multiple hypervisor nodes

### ISSUE THREAD

**Issue by lapd-viosoft** [Kubeinit/kubeinit#24]
Currently, kubeinit supports deploy HA mode (3 master nodes) but on single hypervisor server. It's actually not really HA if the hypervisor server is down. It's better option where master nodes run on different hypervisor server.

**Comment by ccamacho** [comment]
@lapd-viosoft thanks a lot for the feedback, I moved all these issues as cards in a kanban project https://github.com/Kubeinit/kubeinit/projects/1 if you will like to contribute, please feel free to push any PR you will like to have included in the code. When I have some free time I'll try to implement some of them.
