### ISSUE TITLE
Issue with rhel8.0 not existing in the dictionary.

### ISSUE THREAD

**Issue by ccamacho** [Kubeinit/kubeinit#28]
@git4liluo this is the correct place for the issue

My hypervisor is ubuntu. I got the following task failed. It might not be an issue, but I would appreciate your input/advice.

TASK [../../roles/kubeinit_libvirt : Create VM definition for the service nodes] *********************************************************************************
failed: [hypervisor-01] (item=okd-service-01) => {"ansible_loop_var": "item", "changed": false, "cmd": "virt-install --connect qemu:///system --name=okd-service-01 --memory memory=12288 --cpuset=auto --vcpus=8,maxvcpus=16 --os-type=linux --os-variant=rhel8.0 --autostart --network network=kimgtnet0,mac=52:54:00:f2:46:a7,model=virtio --graphics none --noautoconsole --import --disk /var/lib/libvirt/images/okd-service-01.qcow2,format=qcow2,bus=virtio\n", "delta": "0:00:00.791032", "end": "2020-09-29 13:45:49.480230", "item": "okd-service-01", "msg": "non-zero return code", "rc": 1, "start": "2020-09-29 13:45:48.689198", "stderr": "ERROR Error validating install location: Distro 'rhel8.0' does not exist in our dictionary", "stderr_lines": ["ERROR Error validating install location: Distro 'rhel8.0' does not exist in our dictionary"], "stdout": "", "stdout_lines": []}

**Comment by ccamacho** [comment]
@git4liluo weird issue, this is configured here

https://github.com/Kubeinit/kubeinit/blob/11d7332e7d420344ab16b8480dc24fbdf2631a54/kubeinit/roles/kubeinit_libvirt/tasks/10_deploy_service_nodes.yml#L127

Can you please run in you hypervisor:

osinfo-query os
And see if you have available rhel8.0? if not you should have rhl8.0 (note the 'e' is not present).

Just update the playbook1 with the distro and it should work.

Please feel free to ask any questions you have, and if you find any issue also feel free to raise issues in the project's repo (https://www.github.com/kubeinit/kubeinit). Also, it would be awesome if you can star the project to catch up with updates and new features.

Thanks!

**Comment by Swamination** [comment]
I also ran into this issue. Some form of libvirt requirement was unhappy with the profiling of system requirements.
I resolved the issue by updating the osinfo db on the hypervisor (Ubuntu 18.04 LTS):
```
wget https://releases.pagure.org/libosinfo/osinfo-db-20201218.tar.xz (or whatever the latest release is from that site)
sudo apt-get install -y osinfo-db-import
sudo osingo-db-import -v --local osinfo-db-20201218.tar.xz
```
