### ISSUE TITLE
Multiple clusters on the same bare metal?

### ISSUE THREAD

**Issue by git4liluo** [Kubeinit/kubeinit#29]
I used a bare metal to be hypervisor-01, then created a cluster(starting with one master, one worker, one service, one bootstrap) successfully using the tool. I actually wanted to create MANY such SIMPLE clusters on the same bare metal. So my question: How can I create a second cluster on the same bare metal? I think there should be only one hypervisor on one bare metal. BTW, after the cluster is deployed, anyway I can reach/manage it from somewhere else. How can a created cluster have a web interface?

**Comment by ccamacho** [comment]
Hi @git4liluo, deploying multiple clusters is fairly easy with some adjustments I already implemented, please read this guide: https://www.anstack.com/blog/2020/10/04/Multiple-KubeInit-clusters-in-the-same-hypervisor.html

For the external access here you have how to do it (accessing the web interface) https://www.anstack.com/blog/2020/08/25/KubeInit-External-access-for-OpenShift-OKD-deployments-with-Libvirt.html

If you manage to exercise the content of the posts and you find issues, improvements, or new features you might want to implement feel free to push a PR and I'll review it.

Please feel free to ask any questions you have, and if you find any issue also feel free to raise issues in the project's repo (https://www.github.com/kubeinit/kubeinit). Also, it would be awesome if you can star the project to catch up with updates and new features.
