### ISSUE TITLE
Podman container dictates hypervisor environment

### ISSUE THREAD

**Issue by iqre8** [Kubeinit/kubeinit#300]
### Issue
Podman container is Debian based. It seems the container env dictates the hypervisor environment, so when the hypervisor is Centos, you get errors.

### Current workaround:
Run ansible on the same OS as your hypervisors. Only run podman container if your hypervisors are Debian based.

**Comment by gmarcy** [comment]
Containers are now using UBI, and have been fixed to work with all supported hypervisor OS.
