### ISSUE TITLE
Potential hardcoding of subnet

### ISSUE THREAD

**Issue by nadenf** [Kubeinit/kubeinit#321]
In these two files:

kubeinit/kubeinit/roles/kubeinit_nexus/tasks/main.yml
kubeinit/kubeinit/roles/kubeinit_submariner/templates/iptables_hypervisor_nat_config.j2

The 10.0.* subnet is hardcoded and not picked up from the inventory file.

**Comment by ccamacho** [comment]
Fixed by: https://github.com/Kubeinit/kubeinit/pull/336

This file iptables_hypervisor_nat_config.j2 should be removed soon as is deprecated.
