### ISSUE TITLE
Documentation is missing the fact that nodes should not be renamed

### ISSUE THREAD

**Issue by nadenf** [Kubeinit/kubeinit#322]
In the inventory file I renamed my worker nodes to:
```
[worker_nodes]
eks-core ansible_host=10.0.0.6 mac=52:54:00:39:22:52 interfaceid=9edc6913-d6f9-4091-ad11-1138d1caacb1 target=hypervisor-01 type=virtual
eks-task1 ansible_host=10.0.0.7 mac=52:54:00:14:61:67 interfaceid=73139f80-1564-40e4-ba9f-5b0941e780da target=hypervisor-01 type=virtual
eks-task2 ansible_host=10.0.0.8 mac=52:54:00:34:34:47 interfaceid=3584b702-4b70-44be-be6d-0995277b8a6d target=hypervisor-01 type=virtual
```

Which is a problem since Kubeinit needs "worker" in the name for that node to be recognised.

In the documentation and within the inventory it would be good to mention this fact.

**Comment by ccamacho** [comment]
Right, that logic lives here:
https://github.com/Kubeinit/kubeinit/blob/main/kubeinit/roles/kubeinit_prepare/tasks/prepare_groups.yml#L21-L40

maybe we could change it to deprecate the regex in favor of fetching the nodes from that specific groups

**Comment by ccamacho** [comment]
Fixed by: https://github.com/Kubeinit/kubeinit/pull/335
