### ISSUE TITLE
Registry is not accessible with multiple service nodes

### ISSUE THREAD

**Issue by nadenf** [Kubeinit/kubeinit#326]
Using the following inventory:
```
https://gist.github.com/nadenf/73d7cc843c8887c8b5309268fed64c84
```

I get the following error:
```
TASK [../../roles/kubeinit_registry : Check if the registry is up and running] ***************************************************************************************************************************************************************
fatal: [localhost -> 11.0.0.101]: FAILED! => 
{
	"changed": false,
	"cmd": "set -o pipefail\nset -e\ncurl -v --silent --user registryusername:registrypassword https://eks-service1.eks.kubeinit.local:5000/v2/_catalog --stderr - | grep '\\{\"repositories\":'\n# curl -v --silent --user registryusername:registrypassword https://eks-service1.eks.kubeinit.local:5000/v2/openshift/tags/list\n",
	"delta": "0:00:00.060488",
	"end": "2021-05-29 12:49:41.650796",
	"msg": "non-zero return code",
	"rc": 1,
	"start": "2021-05-29 12:49:41.590308",
	"stderr": "",
	"stderr_lines": [],
	"stdout": "",
	"stdout_lines": []
}
```

And nslookup on eks-service1.eks.kubeinit.local indicates that the domain can't be found.

**Comment by ccamacho** [comment]
I'll need to check why it failed for you, I just triggered the end job and it works as it should. https://storage.googleapis.com/kubeinit-ci/jobs/periodic/periodic-eks-libvirt-3-1-periodic-weekly-go/index.html Can you explain here what you changed in the inventory + a description of your environment so I can resproduce it?

**Comment by nadenf** [comment]
From LSB_Release:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
```

And two key changes: (1) Changed from 10.0 -> 11.0 because of a conflict with my network and (2) Added additional nodes e.g. service.

**Comment by nadenf** [comment]
Actually it was caused by me incorrectly setting the bridge mode. Looks good now !

**Comment by nadenf** [comment]
Say we have two nodes (serviceA, serviceB) this will be the process:

1. Registry is installed on serviceA
2. Check if registry is running at URL: serviceA.kubeinit.local
3. Registry is running.
4. Registry is installed on serviceB
5. Check if registry is running at URL: serviceA.kubeinit.local
6. Registry is not running.

Now for some reason serviceB node can not access the registry on serviceA.

**Comment by ccamacho** [comment]
So far there is only one services node with the required services to run the cluster, it will have Bind, Apache, a container registry, and HAProxy. This is not a valid configuration.
