### ISSUE TITLE
Cleanup fails requiring password

### ISSUE THREAD

**Issue by nadenf** [Kubeinit/kubeinit#328]
Trying to run the clean command as documented [here](https://docs.kubeinit.com/usage.html#cleaning-up-the-environment) and getting the follow error message:

```
TASK [../../roles/kubeinit_prepare : gather network facts] ***********************************************************************************************************************************************************************************
fatal: [hypervisor-01]: FAILED! => {
	"ansible_facts": {},
	"changed": false,
	"failed_modules": {
		"ansible.legacy.setup": {
			"failed": true,
			"module_stderr": "sudo: a password is required\n",
			"module_stdout": "",
			"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
			"rc": 1
		}
	},
	"msg": "The following modules failed to execute: ansible.legacy.setup\n"
}
```

Inventory being used is available [here](https://gist.github.com/nadenf/73d7cc843c8887c8b5309268fed64c84
). 

And have no issues completing most of the install steps and logging in to my hypervisor without SSH password.

**Comment by gmarcy** [comment]
Can you try running the ansible-playbook command without specifying --become or --become-user ?  Those are no longer necessary and should be omitted from the command line

**Comment by ccamacho** [comment]
Didnt manage to reproduce this, feel free to reopen if happens again.
