### ISSUE TITLE
Cleanup fails if nodes are undefined

### ISSUE THREAD

**Issue by nadenf** [Kubeinit/kubeinit#330]
It is possible to get into a state where one or more of the nodes are _shut-off_. 
These nodes need to be undefined and not destroyed.

In this file:
```
kubeinit/kubeinit/roles/kubeinit_libvirt/tasks/10_cleanup.yml
```

It tries to destroy the node and then undefine it. But if a node is shut-off the destroy step will fail and undefine won't get a chance to run. One option is to just ignore errors in the destroy step.

**Comment by ccamacho** [comment]
Fixed by https://github.com/Kubeinit/kubeinit/pull/334

**Comment by ccamacho** [comment]
Still failing and reproduced here: https://storage.googleapis.com/kubeinit-ci/jobs/pr/313019047-k8s.ovn-libvirt-3-1-default-2021.06.01.10.30.14-1/index.html

**Comment by gmarcy** [comment]
@ccamacho This is now fixed, right?

**Comment by ccamacho** [comment]
Indeed closing, thanks @gmarcy for the final fix!
