### ISSUE TITLE
Documentation needed for node types

### ISSUE THREAD

**Issue by nadenf** [Kubeinit/kubeinit#331]
It is not clear what the role of each of the nodes are for e.g. master, worker, service.

**Comment by gmarcy** [comment]
I would agree with the service node, as that is in some ways particular to kubeinit and how it sets up the provisioning environment, but how far should kubeinit be going to explain basic kubernetes concepts like master and worker nodes or describing all of the differences in the distributions, etc.?  Other than a link to some generic "What is kubernetes?" site what would you expect us to say in the kubeinit docs?

**Comment by nadenf** [comment]
For me it just needs two things:

1) What the service node is for (and what's installed on it e.g. HAProxy, Apache).
2) Importance of the node naming convention (this should also be in the inventory file)

Everything is much clearer now that the nodes are named controller/compute.
