### ISSUE TITLE
Document / display information on how to use cluster

### ISSUE THREAD

**Issue by nadenf** [Kubeinit/kubeinit#333]
So after the cluster has been setup it would be useful to have the following:

1) URL and CA Cert for the API Server
2) Generated Kubeconfig
3) Sample commands e.g. kubectl get po

It could be either dynamically generated and output from Ansible or simply documented.

**Comment by ccamacho** [comment]
Fixed by: https://github.com/Kubeinit/kubeinit/pull/336/commits/77aa80f7ccdf640e4bbdcfee4c3e7192bdb7296a
