### ISSUE TITLE
ImagePullBackOff after deploying sample app on 4.7.0-0.okd-2021-06-13-090745

### ISSUE THREAD

**Issue by drejmar** [Kubeinit/kubeinit#354]
git checkout 1.0.2

kubeinit/roles/kubeinit_okd/defaults/main.yml

it works with default okd: 4.6.0-0.okd-2021-02-14-205305
it works with openshift: 4.7.1 (able to upgrade to 4.7.16)
it does NOT work with okd: 4.7.0-0.okd-2021-06-13-090745

error pinging docker registry image-registry.openshift-image-registry.svc:5000:
Get "https://image-registry.openshift-image-registry.svc:5000/v2/":
dial tcp: lookup image-registry.openshift-image-registry.svc on 10.0.0.254:53:
no such host

**Comment by gmarcy** [comment]
We've recently been giving this some attention and are in the process of testing a PR (#378) that moves the OKD version from `4.6.0-0.okd-2021-02-14-205305` to  `4.7.0-0.okd-2021-06-19-191547` after addressing a number of issues that were preventing that from working.

**Comment by drejmar** [comment]
Thank you for your update.

Currently not able to install the main branch:
TASK [Check cluster nodes are up and running] 
TASK [../../roles/kubeinit_libvirt : make sure we can execute remote commands in okd-service-01 before continue]
"ssh: connect to host 10.0.0.100 port 22: No route to host"

Prior to this issue I made these changes:
1)
install requirements
  ansible-galaxy collection install --force -r kubeinit/requirements.yml
2)
  install podman on Ubuntu 20.04 (https://podman.io/getting-started/installation)
3)
  edit kubeinit/roles/kubeinit_prepare/tasks/50_ovn_post_setup.yml (replace wait=hv by wait=none) (ovn-nbctl commands get stuck with "--wait=hv")

**Comment by drejmar** [comment]
Still experience the problem described in the first comment.

Installation is done from main branch. It completes successfully, I'm able to login and try to deploy a sample application.

Modified files:
kubeinit/hosts/okd/inventory
kubeinit/group_vars/all.yml
kubeinit/roles/kubeinit_okd/defaults/main.yml

code is pulled from github, image is built and pushed to registry: image-registry.openshift-image-registry.svc:5000

ImagePullBackOff happens when worker2 tries to deploy the image.
It doesn't know how to get to the registry.
