### ISSUE TITLE
Install fails because tmp directory is not writeable

### ISSUE THREAD

**Issue by nadenf** [Kubeinit/kubeinit#374]
**Describe the bug**
Installation is failing due to Ansible being unable to create temp directory.

**To Reproduce**
1. Clone project.
2. Run the "Directly executing the deployment playbook" as described in the README.

**Infrastructure**
 - Hypervisors OS: Ubuntu
 - Version: 21.04

**Deployment command**

```
ansible-playbook \
    --user root \
    -v -i ./hosts/okd/inventory \
    --become \
    --become-user root \
    ./playbooks/okd.yml
```

**Error message**
```
TASK [../../roles/kubeinit_services : Make sure needed packages are installed] *****************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1624737938.0447485-55163-189469634661217 `\" && echo ansible-tmp-1624737938.0447485-55163-189469634661217=\"` echo ~/.ansible/tmp/ansible-tmp-1624737938.0447485-55163-189469634661217 `\" ), exited with result 125", "unreachable": true}
```

**Additional context**

This error message only applies when directly running ansible-playbook and not using podman.

**Comment by nadenf** [comment]
I have tried both options:

1. Seems to be an issue with ssh-copy-id not consistently working when running as root user.
2. Setting ansible.cfg to /tmp/kubeinit works fine.

**Comment by nadenf** [comment]
For option (2) there will need to be a step in the instruction that asks them to pre-create the directory and set permissions to 777. Otherwise Ansible will set it to 700 and the install will fail because it gets created as root and then the non-root user can't access it.

**Comment by ccamacho** [comment]
This issue is not related to a temp dir, can you run please:

```
podman --remote system connection list | sed -e 1d -e 's/[* ].*//' | while read servpod ; do podman --remote system connection remove $servpod ; done
```

**Comment by ccamacho** [comment]
Fixed by: https://github.com/Kubeinit/kubeinit/pull/382
