### ISSUE TITLE
Documentation needed for how to resume installation

### ISSUE THREAD

**Issue by nadenf** [Kubeinit/kubeinit#377]
**Describe the bug**
If the host that Kubeinit is installed on is restarted then the VMs are no longer running. 

It would be useful to document (if it's possible) how to bring back Kubeinit to its previous running state.

**To Reproduce**
1. Install Kubeinit
2. Restart machine
3. Note that VMs are no longer running and it's not clear how to resume them.

**Comment by ccamacho** [comment]
Hi @nadenf this is a goal that we are pursuing, but it's something that is not currently supported. Resume installation is for us to start from the point it failed (if it failed) a deployment.

In the case you turn off the cluster it won't either work, starting from that the following steps as are not persisted., the ip commands like https://github.com/Kubeinit/kubeinit/blob/main/kubeinit/roles/kubeinit_prepare/tasks/50_ovn_post_setup.yml#L102 are lost on a reboot, feel free to try replacing them with a persistent option and we would be glad to integrate them to the code base.
