### ISSUE TITLE
RFE: Support addition of non-os disks

### ISSUE THREAD

**Issue by raghavendra-talur** [Kubeinit/kubeinit#390]
It would help storage developers a great deal if there was an option of adding non-os disks to the worker nodes. These disks can then be used by the local storage https://github.com/openshift/local-storage-operator to make them consumable by https://github.com/rook/rook or other storage operators.

**Comment by raghavendra-talur** [comment]
I am familiar with the virsh/virt-install changes required to add the disks, if you could guide me on the the following two topics I will give it a try to implement this feature myself.

* Field to add to the compute nodes section. I am thinking of 
** extradisk_size=inGB
** extradisk_count=int

* How to handle the validation of the required disk sizes per hypervisor.

**Comment by ccamacho** [comment]
Hello @raghavendra-talur !!

This should be relatively easy to implement, the steps should be:
1- Add the external volumes info in the inventory files, we could extend this information https://github.com/Kubeinit/kubeinit/blob/main/kubeinit/hosts/okd/inventory#L37-L44 to support an array of additional volumes.

Something like
```
...
root_device=/dev/vda
additional_volumes=[{size: 10G, device=/dev/vdb, mount=/mnt/foo},{size: 10G, device=/dev/vdc, mount=/mnt/foo2}]
```

Then here rely on the logic to create attach the volumes:

https://github.com/Kubeinit/kubeinit/blob/main/kubeinit/roles/kubeinit_libvirt/tasks/60_deploy_centos_guest.yml and https://github.com/Kubeinit/kubeinit/blob/main/kubeinit/roles/kubeinit_libvirt/tasks/60_deploy_coreos_guest.yml

So you can plug as many volumes as you need.

If you manage to implement it then Ill fix up the disk usage validation for sure.

Thanks!!!

**Comment by ccamacho** [comment]
@raghavendra-talur any update on this? Do you require anything from us?
