### ISSUE TITLE
Access to Service Machine

### ISSUE THREAD

**Issue by jmcxw** [Kubeinit/kubeinit#480]
Hello

OKD Installation worked fine, now I try to access the service machine but I don't know the credentials and didn't find any. I guess this CentOS machine is also certificate authentication enabled, the problem here for me is, that I haven't found the way to get SSH access on those VMs. I created an additional VM and gave it a static IP for the network which was defined in the Inventory file of the Installation, but this machine isn't able to see anything inside of this network, I guess this has to do with the setup of openvswitch network, which I don't really know anything about.

Can you help me out here, it would be great to have access to this machines, preferable over SSH.

**Comment by gmarcy** [comment]
when you run the services deployment one of the tasks in the kubeinit_bind role will create an external ingress script on the primary (bastion) hypervisor called `create-external-ingress.sh`.  running this should create tunnels for all the service endpoints on the cluster.  you should be able to fetch the kubeadmin password running a command like:
```
echo $(ssh root@nyctea ssh root@10.0.0.100 cat install_dir/auth/kubeadmin-password)
```
console should be available at `https://console-openshift-console.apps.okdcluster.kubeinit.local` from the external machine if you have something like this in /etc/resolv.conf:
```
search okdcluster.kubeinit.local
nameserver <ip of nyctea>
nameserver 8.8.8.8
```

**Comment by ccamacho** [comment]
Tested, let's wait for a docs patch that closes this issue
