### ISSUE TITLE
Failure during task: Add remote system connection definition for bastion hypervisor

### ISSUE THREAD

**Issue by njayakrishna** [Kubeinit/kubeinit#497]
Post the fix for issue 495, I am seeing this error during installation:

TASK [kubeinit.kubeinit.kubeinit_services : Add remote system connection definition for bastion hypervisor] **************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "cmd": ["podman", "--remote", "system", "connection", "add", "service-01", "--identity", "~/.ssh/okdcluster_id_rsa", "ssh://root@fe80::3e7c:3fff:fe4c:ca6e%enp3s0:22/run/user/0/podman/podman.sock"], "delta": "0:00:00.018617", "end": "2021-09-29 04:08:08.381757", "msg": "non-zero return code", "rc": 125, "start": "2021-09-29 04:08:08.363140", "stderr": "Error: parse "ssh://root@fe80::3e7c:3fff:fe4c:ca6e%enp3s0:22/run/user/0/podman/podman.sock": invalid URL escape "%en"", "stderr_lines": ["Error: parse "ssh://root@fe80::3e7c:3fff:fe4c:ca6e%enp3s0:22/run/user/0/podman/podman.sock": invalid URL escape "%en""], "stdout": "", "stdout_lines": []}

**Comment by ccamacho** [comment]
@njayakrishna can you make sure you have IPv6 disabled? root@fe80::3e7c:3fff:fe4c:ca6e%enp3s0:22 should be root@xxx.xxx.xxx.xxx:22

**Comment by njayakrishna** [comment]
Thanks, I disabled IPv6 and got down further. This is a new error I am facing now:
fatal: [localhost -> service-01]: FAILED! => {"attempts": 5, "changed": false, "cmd": "openshift-install gather --dir install_dir bootstrap --bootstrap 10.0.0.200     --master 10.0.0.1\nopenshift-install --dir=install_dir/ wait-for bootstrap-complete --log-level info\n", "delta": "0:20:49.242874", "end": "2021-09-29 18:40:33.887698", "msg": "non-zero return code", "rc": 1, "start": "2021-09-29 18:19:44.644824", "stderr": "level=info msg=Pulling debug logs from the bootstrap machine\nlevel=info msg=Bootstrap gather logs captured here \"/root/install_dir/log-bundle-20210929181944.tar.gz\"\nlevel=info msg=Waiting up to 20m0s for the Kubernetes API at https://api.okdcluster.kubeinit.local:6443...\nlevel=error msg=Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: an error on the server (\"\") has prevented the request from succeeding (get clusteroperators.config.openshift.io)\nlevel=info msg=Use the following commands to gather logs from the cluster\nlevel=info msg=openshift-install gather bootstrap --help\nlevel=fatal msg=failed waiting for Kubernetes API: an error on the server (\"\") has prevented the request from succeeding", "stderr_lines": ["level=info msg=Pulling debug logs from the bootstrap machine", "level=info msg=Bootstrap gather logs captured here \"/root/install_dir/log-bundle-20210929181944.tar.gz\"", "level=info msg=Waiting up to 20m0s for the Kubernetes API at https://api.okdcluster.kubeinit.local:6443...", "level=error msg=Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: an error on the server (\"\") has prevented the request from succeeding (get clusteroperators.config.openshift.io)", "level=info msg=Use the following commands to gather logs from the cluster", "level=info msg=openshift-install gather bootstrap --help", "level=fatal msg=failed waiting for Kubernetes API: an error on the server (\"\") has prevented the request from succeeding"], "stdout": "", "stdout_lines": []}

**Comment by njayakrishna** [comment]
Can you please let me know some clues to fix this? Is it related to DNS configuration in the VMs?

**Comment by ccamacho** [comment]
@njayakrishna so this is specific to OKD, for debugging this you need to provide the information is required when you open the issue.

**Comment by njayakrishna** [comment]
Sorry, I did not understand. Can you please let me know if I should open a new issue?

**Comment by ccamacho** [comment]
@njayakrishna yes please and fill in the information that is required when opening the issue.
