### ISSUE TITLE
quay.io/centos/centos:stream8 is outdated

### ISSUE THREAD

**Issue by drejmar** [Kubeinit/kubeinit#585]
Installing okd 4.9.0 by kubeinit 2.0.1 fails at TASK [kubeinit.kubeinit.kubeinit_services : Install python3]

TASK [kubeinit.kubeinit.kubeinit_services : Install python3] *************************************************************************************************************
fatal: [localhost -> hypervisor-01(drejmar.eu)]: FAILED! => {"changed": false, "cmd": ["podman", "exec", "io-credentials", "dnf", "install", "-y", "python3", "openssh"], "delta": "0:00:05.076773", "end": "2022-01-06 13:12:13.625189", "msg": "non-zero return code", "rc": 132, "start": "2022-01-06 13:12:08.548416", "stderr": "", "stderr_lines": [], "stdout": "Last metadata expiration check: 0:00:49 ago on Thu Jan  6 12:11:20 2022.
Dependencies resolved.

**This series of commands tends to cause the issue:**

podman run --rm -i -t quay.io/centos/centos:stream8
[root@9a064fce332f /]# **dnf**

[root@9a064fce332f /]# **dnf update -y**

Transaction Summary
Install  37 Packages
Upgrade  60 Packages

[root@9a064fce332f /]# **dnf**

[root@9a064fce332f /]# **dnf install python3 -y**

Transaction Summary
Install  4 Packages

Total download size: 1.8 M
Installed size: 7.2 M
Downloading Packages:
(1/4): python3-pip-9.0.3-22.el8.noarch.rpm                                                                                  377 kB/s |  20 kB     00:00
(2/4): python36-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64.rpm                                                             347 kB/s |  19 kB     00:00
(3/4): python3-setuptools-39.2.0-6.el8.noarch.rpm                                                                           1.8 MB/s | 163 kB     00:00
(4/4): platform-python-pip-9.0.3-22.el8.noarch.rpm                                                                          7.3 MB/s | 1.6 MB     00:00

Total                                                                                                                       5.7 MB/s | 1.8 MB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                    1/1
  Installing       : python3-setuptools-39.2.0-6.el8.noarch                                                                                             1/4
  Installing       : platform-python-pip-9.0.3-22.el8.noarch                                                                                            2/4
  Installing       : python36-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64                                                                               3/4
  Running scriptlet: python36-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64                                                                               3/4
  Installing       : python3-pip-9.0.3-22.el8.noarch                                                                                                    4/4
  Running scriptlet: python3-pip-9.0.3-22.el8.noarch                                                                                                    4/4
  Verifying        : python3-pip-9.0.3-22.el8.noarch                                                                                                    1/4
  Verifying        : python36-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64                                                                               2/4
  Verifying        : platform-python-pip-9.0.3-22.el8.noarch                                                                                            3/4
  Verifying        : python3-setuptools-39.2.0-6.el8.noarch                                                                                             4/4

Installed:
  platform-python-pip-9.0.3-22.el8.noarch                        python3-pip-9.0.3-22.el8.noarch           python3-setuptools-39.2.0-6.el8.noarch
  python36-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64

Complete!
### **Illegal instruction**
[root@9a064fce332f /]# dnf
Traceback (most recent call last):
  File "/usr/bin/dnf", line 57, in <module>
    from dnf.cli import main
  File "/usr/lib/python3.6/site-packages/dnf/__init__.py", line 30, in <module>
    import dnf.base
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 32, in <module>
    from dnf.comps import CompsQuery
  File "/usr/lib/python3.6/site-packages/dnf/comps.py", line 36, in <module>
    import libcomps
  File "/usr/lib64/python3.6/site-packages/libcomps/__init__.py", line 1, in <module>
    from ._libpycomps import *
ImportError: /usr/lib64/python3.6/site-packages/libcomps/_libpycomps.so: invalid ELF header

Can you use
tgagor/centos:stream8
instead?

**Comment by drejmar** [comment]
Thanks for your reply.

This is the series of commands which caused the issue several times (yesterday):
dnf update -y
dnf install python3 -y
dnf install openssh -y

Image was deleted between trials:

podman rmi quay.io/centos/centos:stream8
Untagged: quay.io/centos/centos:stream8
Deleted: dc28896b677ede1d5bd9f7d596807c14aaf3f3acf2abf4b4d19dcd0e5d3211fb
podman run --rm -i -t quay.io/centos/centos:stream8
Trying to pull quay.io/centos/centos:stream8...
Getting image source signatures
Copying blob 203c612978b4 done
Copying blob e3ff3ac72de5 done
Copying blob 5186e8704530 done
Copying blob 758c773fb4aa done
Copying config dc28896b67 done
Writing manifest to image destination
Storing signatures

Today I cannot reproduce it.

My guess is that some file is/was faulty on one of centos mirrors. Today I cannot prove this, because I downloaded it from all known mirrors in Germany and its contents were intact:

wget http://de.mirrors.clouvider.net/CentOS/8-stream/BaseOS/x86_64/os/Packages/python3-libcomps-0.1.16-2.el8.x86_64.rpm -O python3-libcomps.rpm.101
...
wget https://mirrors.xtom.de/centos/8-stream/BaseOS/x86_64/os/Packages/python3-libcomps-0.1.16-2.el8.x86_64.rpm -O python3-libcomps.rpm.134

diff python3-libcomps.rpm.101 python3-libcomps.rpm.102
...
diff python3-libcomps.rpm.101 python3-libcomps.rpm.134


dnf provides /usr/lib64/python3.6/site-packages/libcomps/_libpycomps.so
python3-libcomps-0.1.18-1.el8.x86_64 : Python 3 bindings for libcomps library
Repo        : baseos

cat /var/log/dnf.librepo.log | grep libcomps

2022-01-16T08:13:45+0000 INFO Downloading: http://ftp.hosteurope.de/mirror/centos.org/8-stream/BaseOS/x86_64/os/Packages/libcomps-0.1.18-1.el8.x86_64.rpm
2022-01-16T08:13:45+0000 INFO Downloading: http://ftp.hosteurope.de/mirror/centos.org/8-stream/BaseOS/x86_64/os/Packages/python3-libcomps-0.1.18-1.el8.x86_64.rpm

2022-01-16T07:38:31+0000 INFO Downloading: http://centos.schlundtech.de/8-stream/BaseOS/x86_64/os/Packages/libcomps-0.1.18-1.el8.x86_64.rpm
2022-01-16T07:38:31+0000 INFO Downloading: http://centos.schlundtech.de/8-stream/BaseOS/x86_64/os/Packages/python3-libcomps-0.1.18-1.el8.x86_64.rpm

2022-01-16T07:46:44+0000 INFO Downloading: http://ftp.rz.uni-frankfurt.de/pub/mirrors/centos/8-stream/BaseOS/x86_64/os/Packages/libcomps-0.1.18-1.el8.x86_64.rpm
2022-01-16T07:46:45+0000 INFO Downloading: http://ftp.rz.uni-frankfurt.de/pub/mirrors/centos/8-stream/BaseOS/x86_64/os/Packages/python3-libcomps-0.1.18-1.el8.x86_64.rpm

https://pastebin.com/xKimWaNJ

I would still suggest that you use
tgagor/centos:stream8
image, because it's updated weekly

**Comment by gmarcy** [comment]
@drejmar I opened an [issue](https://gitlab.com/redhat/centos-stream/release-engineering/releng-tools/-/issues/1) against the centos releng-tools project.  They have updated the [image at quay](https://quay.io/repository/centos/centos?tab=tags) and have indicated that they will continue to do so in the future.

**Comment by drejmar** [comment]
@gmarcy Thanks for resolving this
