### ISSUE TITLE
Customization for openSUSE Leap 15.3

### ISSUE THREAD

**Issue by berndgz** [Kubeinit/kubeinit#635]
Great project, I like it, but is it customizable for openSUSE Leap 15.3?

**Comment by ccamacho** [comment]
Hi @berndgz!!

Where exactly you want to use it? In the HVs? In the guests? 

In the hypervisor a it should work out of the box, in the guests it will depends on the k8s distro you are deploying (i.e. OKD only works with FCOS) or do you have another distro you will like to integrate?

**Comment by berndgz** [comment]
Hi @ccamacho,

the idea is a chain with: Leap 15.3 > QEMU-KVM > libvirt > OKD with FCOS

**Comment by ccamacho** [comment]
I don't see any impediment in that configuration, just making sure the packages names and repos are ok. Just notice that it works on RHEL, CentOS and Fedora

**Comment by berndgz** [comment]
I am not familiarized with Ansible, do I have to check the playbooks?

**Comment by ccamacho** [comment]
Did you try already? Did you get an error? Try an initial deployment let's say with CentOS once you know it works as it should, reinstall the hypervisor an repeat the steps. If you get errors we can try to debug them.

**Comment by berndgz** [comment]
Should I use Wicked or Network Manager on the host system (Leap 15.3)?

**Comment by ccamacho** [comment]
@berndgz I never tried an install in Leap, Wicked wasn't used at all so I assume that will not work.

**Comment by berndgz** [comment]
@ccamacho you are right, Leap needs libvirt Agnostic Install.
