### ISSUE TITLE
Make sure there is enough free space 

### ISSUE THREAD

**Issue by linuxliste** [Kubeinit/kubeinit#68]
Hi, 
My test system has only one filesystem. / has enough space, however kubeinit say to me, ""msg": "It seems there is not enough disk space (Required: 302.5 Total: 0)""

TASK [../../roles/kubeinit_validations : Make sure there is enough free space] ***************************************************************************************************************************************************************
fatal: [hypervisor-01]: FAILED! => {
    "assertion": "kubeinit_validations_libvirt_free_space.stdout[:-1]|int > kubeinit_validations_libvirt_disk_usage|float * 1.1",
    "changed": false,
    "evaluated_to": false,
    "msg": "It seems there is not enough disk space (Required: 302.5 Total: 0)"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
hypervisor-01              : ok=4    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

[root@lab08 kubeinit]# df -h /
Filesystem                         Size  Used Avail Use% Mounted on
/dev/mapper/vg_seyyah-fedora_root  901G   92G  809G  11% /
[root@las08 kubeinit]# 

kubeinit can check /,  if libvirt does not have separate file system.?
Thanks.

**Comment by ccamacho** [comment]
Hi @linuxliste,

Can you run:

df -BG --output=avail /car/lib/libvirt

Just to check the fs of the libvirt folder, to check why it reports 0 in your env.

Thanks

**Comment by ccamacho** [comment]
Closing as not getting feedback here, in theory, /var/lib/libvirt must have enough space to host the guests. What we do in the validation is to verify that the FS on /var/lib/libvirt has enough space.
