### ISSUE TITLE
Use existing network

### ISSUE THREAD

**Issue by Bilal-io** [Kubeinit/kubeinit#69]
Hi!

Is there a way to make the OKD deployment use an existing network, instead of creating a virtual network? Keeping in mind that I also want to expose the service externally.

Meanwhile, I will try to edit the files myself to achieve that.
Thank you!

**Comment by ccamacho** [comment]
@Bilal-io all the information related to the network where is deployed the cluster is defined in the inventory.

One thing, you must be careful as the network bridge is removed in every deployment (make sure you don't nuke your environment if you are using it for other guests). Whatever you do seems interesting to integrate the cluster in other existing nets, feel free to share your feedback and any improvement, we might even document how to do it. Thanks!

**Comment by Bilal-io** [comment]
@ccamacho I had to go a different route for now. But I will revisit this repo for sure.
I am interested in using assisted-installer/assisted-service to deploy a cluster, but for OKD instead of OpenShift, not sure if that's technically possible though.
