### ISSUE TITLE
ssh key generated as okdcluster_id_rsa, but playbook needs kubeinit_id_rsa

### ISSUE THREAD

**Issue by SupremeGit** [Kubeinit/kubeinit#707]
**Describe the bug**

kubeinit-facts is given okdcluster as the cluster name (kubeinit_cluster_distro + 'cluster') and we see tasks like this:
~~~
TASK [kubeinit.kubeinit.kubeinit_prepare : Add kubeinit_spec facts to cluster facts] ********************************************************************************************************
changed: [localhost] => {"add_host": {"groups": ["kubeinit_cluster"], "host_name": "okdcluster", "host_vars": {"compute_count": "1", "controller_count": "3", "distro": "okd", "distro_role": "kubeinit_openshift"}}, "changed": true}
~~~

keys are generated as okdcluster_id_rsa etc.

But then the generated ssh config file references ssh key named kubeinit_id_rsa which does not exist as you can see in task below:

~~~
TASK [kubeinit.kubeinit.kubeinit_prepare : Create ssh config file from template] 
.SNIP.

TASK [kubeinit.kubeinit.kubeinit_prepare : Print the contents of the result] ****************************************************************************************************************
changed: [localhost] => {"changed": true, "cmd": ["cat", "/home/jss/.ssh/okdcluster_config"], "delta": "0:00:00.002621", "end": "2022-11-26 02:57:25.870493", "msg": "", "rc": 0, "start": "2022-11-26 02:57:25.867872", "stderr": "", "stderr_lines": [], "stdout": "Host hypervisor-01\n  Hostname nyctea\n  IdentityFile /home/jss/.ssh/kubeinit_id_rsa\n  UserKnownHostsFile /dev/null\n  StrictHostKeyChecking accept-new\n\nHost nyctea\n  Hostname censored\n  IdentityFile /home/jss/.ssh/kubeinit_id_rsa\n  UserKnownHostsFile /dev/null\n  StrictHostKeyChecking accept-new", "stdout_lines": ["Host hypervisor-01", "  Hostname nyctea", "  IdentityFile /home/jss/.ssh/kubeinit_id_rsa", "  UserKnownHostsFile /dev/null", "  StrictHostKeyChecking accept-new", "", "Host nyctea", "  Hostname also_censored", "  IdentityFile /home/jss/.ssh/kubeinit_id_rsa", "  UserKnownHostsFile /dev/null", "  StrictHostKeyChecking accept-new"]}
~~~
note where it says "IdentityFile /home/jss/.ssh/kubeinit_id_rsa"

Result is that playbook then fails when attempting to gather facts:
~~~
TASK [Gathering Facts] **********************************************************************************************************************************************************************
fatal: [hypervisor-01]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"nyctea\". Make sure this host can be reached over ssh: Warning: Identity file /home/jss/.ssh/kubeinit_id_rsa not accessible: No such file or directory.\nWarning: Permanently added 'censored' (ED25519) to the list of known hosts.\r\nno such identity: /home/jss/.ssh/kubeinit_id_rsa: No such file or directory\r\nroot@censored: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}
~~~

**To Reproduce**
1. follow instructions,
2. see error

**Expected behavior**
success

**Screenshots**
none

**Infrastructure**
fedora 36, fully patched

**Deployment command**

```
ansible-playbook     -v --user root     -e kubeinit_spec=okd-libvirt-3-1-1 -e hypervisor_hosts_spec='[{"host":"hypervisor-01","ansible_host":"nyctea","ssh_hostname":"censored"}]'    -i ./kubeinit/inventory.yml     ./kubeinit/playbook.yml
```

**Inventory file diff**

Run the following command:

```
diff \
    <(curl https://raw.githubusercontent.com/Kubeinit/kubeinit/main/kubeinit/hosts/k8s/inventory) \
    <(curl https://raw.githubusercontent.com/Kubeinit/kubeinit/main/kubeinit/hosts/okd/inventory)
```

And paste the output:

```
That command is nonsense, those urls for inventory file give 404 not found, and the inventory now is empty, replaced by 
-e hypervisor_hosts_spec=blah
on command line
```

**Additional context**
have aliased nytea to ansible & libvirt host, and can ssh to nyctea via ssh key

**Comment by SupremeGit** [comment]
I've now got past that, by copying my existing ssh keys into place at kubeinit_id_rsa etc.

Now fails at:
~~~
    "msg": "It seems there is not enough disk space (Required: {'hypervisor-01': '125'} Available: {'hypervisor-01': 23})"
~~~
It is looking for space specifically at:   /var/lib/libvirt
Which only has 23 GB.

Why it it looking there? 
I have about 50 storage pools for libvirt, and I've stopped all of them except for one, so there is one active pool with 473 GB free. Why does it not check this one active pool and use that.
/var/lib/libvirt is not even an active pool/

Disappointing.

**Comment by SupremeGit** [comment]
ps thank you for giving me a heart attack with the tasks:

TASK [kubeinit.kubeinit.kubeinit_libvirt : Destroy vms]
and
TASK [kubeinit.kubeinit.kubeinit_libvirt : Undefine vms]
and
TASK [kubeinit.kubeinit.kubeinit_libvirt : Remove VMs storage]

Watching  those tasks blast through 100 or so of my VMs and just barely fail to obliterate them due to a fragile conditional was an awesome thrill.

No confirmation, no warning and delay, to give user a chance to exit, just full steam ahead.
Great fun.

**Comment by SupremeGit** [comment]
eventually gets as far as this, and then fails:
~~~
TASK [kubeinit.kubeinit.kubeinit_services : Start okdcluster-provision.service] *************************************************************************************************************
task path: /home/jss/.ansible/collections/ansible_collections/kubeinit/kubeinit/roles/kubeinit_services/tasks/create_managed_service.yml:69
fatal: [localhost -> hypervisor-01(nyctea)]: FAILED! => {"changed": false, "msg": "Unable to start service okdcluster-provision: Job for okdcluster-provision.service failed because the control process exited with error code.\nSee \"systemctl --user status okdcluster-provision.service\" and \"journalctl --user -xeu okdcluster-provision.service\" for details.\n"}
~~~

still disappointing, esp as suggested systemctl & journalctl commands provide none of the promised details.

**Comment by SupremeGit** [comment]
When i try to start the  container manually:
~~~
# /usr/bin/podman start okdcluster-provision
Error: OCI runtime error: unable to start container "dcba65f9a7e206f41b8d412c2247d4ddc2a6c80a3341c4bb40a0a854e622a529": crun: error executing hook `/usr/libexec/oci/hooks.d/oci-systemd-hook` (exit code: 1)
~~~

So i investigate and find:
https://bugzilla.redhat.com/show_bug.cgi?id=1831776
which has:
~~~
Matthew Heon 2020-05-05 15:44:37 UTC
We stopped packaging oci-systemd-hook some time ago; Podman does not require it, and the package should have an explicit Obsoletes: oci-systemd-hook in it. Unless you have a good reason to retain it, I would remove oci-systemd-hook.
~~~

So kubeinit is using this thing called oci-sytemd-hook.
A thing which was obsolete and deprecated 2 1/2 years ago.
A thing which is now unnecessary, and broken.

Does anyone actually use this kubeinit?
Is anyone maintaining this project?
Is it possible to make this work?

If this project is now unmaintained and broken, would it not be advisable to update the README to warn people that the project no longer works, and thus save people from having their time wasted?

**Comment by ccamacho** [comment]
Hi we dont use oci-systemd-hook as "OCI systemd hooks enable running systemd in a OCI runc/docker container"

We do not support docker or runc, try to run it in a fresh installed hypervisor.

Try taking a look to the docs (at least the readme), it is required to have a "fresh deployed server" with enough RAM and disk space, these kind of deployments requires some extra knowledge about the underlying network that is configured. That is the reason we do not expect you to run this in an environment with other workloads.

Cheers.
