### ISSUE TITLE
Might be useful to check/warn for obsolete/deprecated oci-systemd-hook

### ISSUE THREAD

**Issue by SupremeGit** [Kubeinit/kubeinit#709]
**Describe the bug**
Build fails if obsolete/deprecated oci-systemd-hook is installed

**To Reproduce**
1. Run playbook to deploy on libvirt host
2. Watch it go through much preparation & start various containers on host, haproxy etc,
3. Watch it fail to start container okdcluster-provision
4. Try to manually start container okdcluster-provision and see it fails with:
~~~
# /usr/bin/podman start okdcluster-provision
Error: OCI runtime error: unable to start container "dcba65f9a7e206f41b8d412c2247d4ddc2a6c80a3341c4bb40a0a854e622a529": crun: error executing hook `/usr/libexec/oci/hooks.d/oci-systemd-hook` (exit code: 1)
~~~

**Expected behavior**
Container runs & provisions okd cluster

**Screenshots**
none

**Infrastructure**
 - Hypervisors OS: Fedora
 - Version: 36, fully updated on 25/11/2022

**Deployment command**

```
ansible-playbook -v --user root -e kubeinit_spec=okd-libvirt-3-1-1 -e hypervisor_hosts_spec='[{"host":"hypervisor-01","ansible_host":"nyctea","ssh_hostname":"censored"}]'    -i ./kubeinit/inventory.yml     ./kubeinit/playbook.yml
```

**Inventory file diff**
No point.

**Additional context**
This bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1831776
indicates oci-systemd-hook was obsolete, deprecated, and unnecesssary, 2 1/2 years ago.

Turns out i had an orphaned oci-systemd-hook-1:0.2.0-2.git05e6923.fc31 left behind, on my fc36 system, which has been upgraded through many fedora releases.

After removing the obsolete package  okdcluster-provision container did start up.
Unfortunately it has now failed a bit later at:
~~~
TASK [kubeinit.kubeinit.kubeinit_services : Install cluster authorized keys] **
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: deprecated() got an unexpected keyword argument 'name'
~~~

groan.

**Comment by ccamacho** [comment]
Hi we dont use oci-systemd-hook as "OCI systemd hooks enable running systemd in a OCI runc/docker container"

We do not support docker or runc, try to run it in a fresh installed hypervisor.
