### ISSUE TITLE
okdcluster-provision container fails due to updated python3-pyOpenSSL/cryptography, with load_pkcs7_data TypeError 

### ISSUE THREAD

**Issue by SupremeGit** [Kubeinit/kubeinit#710]
**Describe the bug**
TASK [kubeinit.kubeinit.kubeinit_services : Install cluster authorized keys] ***
fails with:
 load_pkcs7_data TypeError: deprecated() got an unexpected keyword argument 'name'

**To Reproduce**
1. run playbook
2. See error

**Expected behavior**
success

**Screenshots**
none

**Infrastructure**
 - Hypervisors OS: fedora
 - Version: 36

**Deployment command**

```
ansible-playbook     -v --user root     -e kubeinit_spec=okd-libvirt-3-1-1 -e hypervisor_hosts_spec='[{"host":"hypervisor-01","ansible_host":"nyctea","ssh_hostname":"blah"}]'    -i ./kubeinit/inventory.yml     ./kubeinit/playbook.yml
```

**Inventory file diff**
```
nope
```

**Additional context**
Playbook fails at:
~~~
TASK [kubeinit.kubeinit.kubeinit_services : Install cluster authorized keys] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: deprecated() got an unexpected keyword argument 'name'
~~~

more details:
~~~
failed: [localhost -> okdcluster-provision] (item=ssh-rsa ***SNIP big uglykey** okdcluster ansible-controller) => {"ansible_loop_var": "item", "changed": false, "item": "ssh-rsa ***SNIP big uglykey** okdcluster ansible-controller", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1669519802.057198-184676-207797955001957/AnsiballZ_authorized_key.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1669519802.057198-184676-207797955001957/AnsiballZ_authorized_key.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1669519802.057198-184676-207797955001957/AnsiballZ_authorized_key.py\", line 48, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.posix.authorized_key_payload_siibnpbp/ansible_ansible.posix.authorized_key_payload.zip/ansible_collections/ansible/posix/plugins/modules/authorized_key.py\", line 217, in <module>\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 656, in _load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 626, in _load_backward_compatible\n  File \"/tmp/ansible_ansible.posix.authorized_key_payload_siibnpbp/ansible_ansible.posix.authorized_key_payload.zip/ansible/module_utils/urls.py\", line 115, in <module>\n  File \"/usr/local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py\", line 50, in <module>\n    import OpenSSL.crypto\n  File \"/usr/local/lib/python3.6/site-packages/OpenSSL/__init__.py\", line 8, in <module>\n    from OpenSSL import SSL, crypto\n  File \"/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py\", line 19, in <module>\n    from OpenSSL.crypto import (\n  File \"/usr/local/lib/python3.6/site-packages/OpenSSL/crypto.py\", line 3232, in <module>\n    name=\"load_pkcs7_data\",\nTypeError: deprecated() got an unexpected keyword argument 'name'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
~~~

Looks like some other ppl have recently been having similar issues eg:
https://github.com/pyca/pyopenssl/issues/1151

**Comment by ccamacho** [comment]
Looks like something specific to your env. Ill trigger a CI job to show it on the status page as all the previous deployments were local (last Friday), maybe this is because you have an old version of ansible, again use a fresh deployed env.

**Comment by SupremeGit** [comment]
No, it's not due to old ansible. My ansible is version 5.9.0-1.fc36, which is the latest available for f36.

It really looked to me like a problem with the pyOPenSSL in the container, but if noone else is seeing the issue, then i guess it must be my env, as you say. 

Apologies re some of these tickets I've filed, when i started hitting these issues it seemed to me like kubeinit was not being kept up to date, and was starting to decay, but that seems not to be the case.

**Comment by SupremeGit** [comment]
Anyway, re this requirement for a freshly installed server, it's not really reasonable to expect users to have a fresh hypervisor. Especially not when it has to have 120 GB of RAM and many cores. Most people do not have a system like that lying around gathering dust waiting to be dedicated to OKD.

It is reasonable that people may want to deploy & test OKD on a hypervisor which is already being used for other development/test purposes as well.

The point of a hypervisor is that it runs many things. If i want do deploy openshift or OKD on vmware at work for example, i don't go and ask for a freshly installed empty vsphere instance, even a single fresh esx host. I expect it to deploy reliably onto existing infrastructure.

The OKD installation uses a boostrap node to do much of the heavy lifting. That is the only "freshly deployed env" we should need. The rest of the bastion things like the haproxy for load balancing and the okdcluster-provision, are running in containers, which should insulate them from issues caused by versions of this & that on the hypervisor. Thats the point of running them in containers.

All the hypervisor needs to do is run ansible, host some containers (if no separate bastion node) & and libvirt network & vms, plus some DNS. I don't see why it should need to be "fresh".

Having said that though, obviously a fresh environment will avoid problems like the one i had with obsolete oci-systemd-hook being present on my system. So i apologise for raising a ticket abt that. And i appreciate you don't have time to debug user's screwed up environments. So if that's the reason behind the fresh environment requirement, then fair enough.

**Comment by SupremeGit** [comment]
Oh well, i will install a fresh f36 as an alternate boot option, on my server. Then run kubeinit from that, and if it works, then i'll boot back up into my trusty non-fresh f36, and see i can work out what is going wrong there. Whatever it is i guess its my problem not yours.
