### ISSUE TITLE
Kubeinit 20.04 repository is currently broken

### ISSUE THREAD

**Issue by UniversalSuperBox** [Kubeinit/kubeinit#774]
Thank you for kubeinit!

**Describe the bug**

The repository for kubeinit on Ubuntu 20.04 is currently broken. When attempting to install podman, the following error is received:

```
Get:1 https://provo-mirror.opensuse.org/repositories/home:/kubeinit/xUbuntu_20.04  podman 100:4.7.1-1 [21.3 MB]
Err:1 https://provo-mirror.opensuse.org/repositories/home:/kubeinit/xUbuntu_20.04  podman 100:4.7.1-1
  File has unexpected size (21316608 != 21326904). Mirror sync in progress? [IP: 91.193.113.70 443]
  Hashes of expected file:
   - SHA256:878d666829b2d9625f82cccaf9a1b94f2cddaee87cceb02765c71b87974ff441
   - SHA1:864179d94c5e09f03c2cfbe1434512190a3b7726 [weak]
   - MD5Sum:18ae4bc9ad3062347ac5bb8e06d26059 [weak]
   - Filesize:21326904 [weak]
```

It is correct. The file currently in the repository does not match the repository metadata.

**To Reproduce**
1. Add https://download.opensuse.org/repositories/home:/kubeinit/xUbuntu_20.04 to a sources.list file with appropriate signing keys
2. Run `apt-get update`
3. Run `apt install podman`

**Expected behavior**

Podman is installed.

**Comment by ccamacho** [comment]
Packages should be up and running here: https://build.opensuse.org/project/monitor/home:kubeinit
