### ISSUE TITLE
OKD UI not opening 

### ISSUE THREAD

**Issue by ManojDhanorkar** [Kubeinit/kubeinit#8]
Let me thank you first for making this available. 

I can do oc get nodes, however when using the UI the firefox errors out. Secure Connection Failed
![Screenshot 2020-08-24 at 4 22 08 PM](https://user-images.githubusercontent.com/11264479/91037362-83a51000-e626-11ea-8f1b-7427f74ddb70.png)

Any help around this is appreciated.

**Comment by ManojDhanorkar** [comment]
Firefox version 68.11 for CentOS linux ( 8.2)

**Comment by sonicwilson** [comment]
you may need to run something like this to get the url
 **The OpenShift web console runs as pods in the openshift-console project and is managed by an operator running in the openshift-console-operator project. You can discover the URL by listing the route.

[hostx@workstation ~]$ oc get routes -n openshift-console
NAME       HOST/PORT                                             ...  PORT   ...
console    **console-openshift-console.apps.cluster.example.com**    ...  https  ...
downloads  downloads-openshift-console.apps.cluster.example.com  ...  http   ...

**Comment by ccamacho** [comment]
Hi!

The openshift web console runs as a virtual host that must be reachable from the internal host network, this must be reached by the DNS registry like http://console-openshift-console.apps.watata.kubeinit.local/  <- that's the default zone we create from the playbook

If you have access to the graphical UI from the host, write that URL in the browser and it should show up.

Remember that 10.0.0.0/24 is a NAT network inside the virtualization host (Im about to write some post to show how to reach it from an external interface) so you need to fetch it internally right now.

**Comment by ManojDhanorkar** [comment]
I tried to do the VNC to above mentioned url  https://console-openshift-console.apps.watata.kubeinit.local/ . 

case 1 :  updated  /etc/hosts on base host( hypervisor host) and tried to access above url.. same error.
case 2 :  also  installed GUI packages and firefox on service host and started VNC server on service host.  connected to VNC server of service host and access firefox directly using the url. 

However still the same issue. Looks like fireforx is failing TLS check.

**Comment by ManojDhanorkar** [comment]
Thanks for your quick inputs

**Comment by ccamacho** [comment]
Hi @ManojDhanorkar I put this together to show you the proper way to access the cluster from an external location:

https://www.anstack.com/blog/2020/08/25/KubeInit-External-access-for-OpenShift-OKD-deployments-with-Libvirt.html

It is not published yet as it's an early draft, but it will show you how to do it.

**Comment by ManojDhanorkar** [comment]
Thank you very much.
