### ISSUE TITLE
Contact via a slack of similar channel?  

### ISSUE THREAD

**Issue by christopherwelsh** [Kubeinit/kubeinit#87]
Sorry for writing here as I do not think this is the best place. I wonder if you could direct me to a slack channel or similar, where I can quickly ask a couple of implementation questions? I am ready to install this but am a little unsure of one or two of the inventory options. Thx

Christopher

**Comment by ccamacho** [comment]
Hi @christopherwelsh sure thing, feel free to PM directly on the Kubernetes's slack workspace (#kubeinit in the Kubernetes slack is requested but not yet created) Or in IRC #kubeinit in Freenode. Any question/feedback/implementation question is welcomed.

**Comment by christopherwelsh** [comment]
Thx, it is about 8:00am here now. What time AU fits best for u?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ccamacho** [comment]
Ohh my gosh xD I'm CET based, I think >17hrs in your time zone. Let's try to speak then, thanks for trying reaching out.
