### ISSUE TITLE
Is the deployment ready for production?

### ISSUE THREAD

**Issue by brainwang** [Kubeinit/kubeinit#9]

**Comment by ccamacho** [comment]
Hi @brainwang !

Thanks for asking, please if you feel this project is useful to you consider to star this repository to keep in touch.

About your question, it depends on what you mean for production-ready?

We use in the deployment stable releases of OKD and Kubevirt which are GA'ed in the downstream releases of OpenShift, we also use stable versions of Libvirt, BIND, HAProxy, Apache, and NFS. So, **All the software deployed is production-ready**.

Then, we have the underlying infrastructure, in this case, we are using a single bare-metal node for the deployment, so if you have redundant hardware, this can be pretty much used for production workloads.

Also, whats this production-ready deployment will be used for?
  - Continuous integration environments? Sure thing it will work.
  - Live systems for internal usage? Also should work.
  - Big scale deployments? Hmmm, in this case, you should take into consideration the deployment sizing based on your applications and the estimated workload, how many worker nodes you will have and how many bare-metal nodes you will use (for this I'm working on another post to show how to deploy a multi-node libvirt cluster to run the deployment, so, each master node will be in a different hypervisor, and the worker nodes spread across the cluster). Also the HAProxy might be replaced with specific load balancing HW (i.e. an F5 load balancer).

Remember that the main difference from using downstream products or upstream projects is the support you will get (there is no support for upstream projects), so, as long as you know what you are doing and feel confident to support it by yourself, upstream projects should be production-ready always. 

Don't forget to star this project! ;) and have a nice weekend.
